// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutGenerator.Infrastructure.Data;

#nullable disable

namespace WorkoutGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    [Migration("20260422034449_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutExerciseId"));

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            WorkoutExerciseId = 1,
                            ExerciseId = 1,
                            Order = 1,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            WorkoutExerciseId = 2,
                            ExerciseId = 2,
                            Order = 2,
                            Reps = 8,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            WorkoutExerciseId = 3,
                            Duration = 60,
                            ExerciseId = 3,
                            Order = 3,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Strength"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cardio"
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.DifficultyLevel", b =>
                {
                    b.Property<int>("DifficultyLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyLevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DifficultyLevelId");

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            DifficultyLevelId = 1,
                            Name = "Beginner"
                        },
                        new
                        {
                            DifficultyLevelId = 2,
                            Name = "Intermediate"
                        },
                        new
                        {
                            DifficultyLevelId = 3,
                            Name = "Advanced"
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyLevelId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            CategoryId = 1,
                            DifficultyLevelId = 2,
                            ExerciseDescription = "Chest exercise with barbell",
                            ExerciseName = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 2,
                            CategoryId = 1,
                            DifficultyLevelId = 2,
                            ExerciseDescription = "Leg exercise with barbell",
                            ExerciseName = "Squat"
                        },
                        new
                        {
                            ExerciseId = 3,
                            CategoryId = 2,
                            DifficultyLevelId = 1,
                            ExerciseDescription = "Core stability exercise",
                            ExerciseName = "Plank"
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("WorkoutDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("WorkoutTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("WorkoutId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            WorkoutId = 1,
                            CoachId = 1,
                            CustomerId = 2,
                            IsArchived = false,
                            IsTemplate = false,
                            WorkoutDescription = "Simple beginner workout",
                            WorkoutTitle = "Full Body Beginner"
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Coach", b =>
                {
                    b.HasBaseType("WorkoutGenerator.Domain.ApplicationUser");

                    b.HasDiscriminator().HasValue("Coach");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coach Mike",
                            Phone = "12345678"
                        });
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Customer", b =>
                {
                    b.HasBaseType("WorkoutGenerator.Domain.ApplicationUser");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.HasIndex("CoachId");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "John Doe",
                            Phone = "87654321",
                            CoachId = 1
                        });
                });

            modelBuilder.Entity("WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutGenerator.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutGenerator.Domain.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Exercise", b =>
                {
                    b.HasOne("WorkoutGenerator.Domain.Category", "Category")
                        .WithMany("Exercises")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutGenerator.Domain.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Exercises")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DifficultyLevel");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Workout", b =>
                {
                    b.HasOne("WorkoutGenerator.Domain.Coach", "Coach")
                        .WithMany("Workouts")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutGenerator.Domain.Customer", "Customer")
                        .WithMany("Workouts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coach");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Customer", b =>
                {
                    b.HasOne("WorkoutGenerator.Domain.Coach", "Coach")
                        .WithMany("Customers")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Category", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.DifficultyLevel", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Coach", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("WorkoutGenerator.Domain.Customer", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
